import { useMemo, useState } from 'react';
import { severityConfig } from './SeveritySummary';
import { applyIssueFix, generateIssueTests, applyIssueTests } from '../services/analysisService';
import { useToast } from '../hooks/useToast';
import { CopyCodeButton } from './MarkdownRenderer';
import CreatePrModal from './CreatePrModal';

const categoryLabels = {
  bug: 'Bug',
  security: 'Security',
  performance: 'Performance',
  'code-smell': 'Code Smell',
};

const severityOrder = { critical: 0, high: 1, medium: 2, low: 3 };

function IssueRow({ issue, analysisId, readOnly }) {
  const toast = useToast();
  const [expanded, setExpanded] = useState(false);
  const [issueState, setIssueState] = useState(issue);
  const [isApplying, setIsApplying] = useState(false);
  const [applyError, setApplyError] = useState('');

  const [isGeneratingTests, setIsGeneratingTests] = useState(false);
  const [generatedTestContent, setGeneratedTestContent] = useState('');
  const [isApplyingTests, setIsApplyingTests] = useState(false);
  const [testApplyError, setTestApplyError] = useState('');
  const [testApplySuccess, setTestApplySuccess] = useState('');

  const [isPrModalOpen, setIsPrModalOpen] = useState(false);
  const [prModalBranchType, setPrModalBranchType] = useState('fix');

  const cfg = severityConfig[issueState.severity] || severityConfig.low;
  const effectiveAnalysisId = issueState.analysisId || analysisId;

  const handleApplyFix = async (e) => {
    e.stopPropagation();
    if (!effectiveAnalysisId || !issueState._id || isApplying) return;
    setIsApplying(true);
    setApplyError('');
    try {
      const result = await applyIssueFix(effectiveAnalysisId, issueState._id);
      setIssueState((prev) => ({ ...prev, ...result.issue }));
      toast.success(
        `Fix applied to branch "${result.branch}". You can now open a Pull Request.`,
        'Fix Applied'
      );
    } catch (err) {
      const msg = err.response?.data?.message || err.message || 'Failed to apply fix.';
      setApplyError(msg);
      toast.error(msg, 'Apply Fix Failed');
      setIssueState((prev) => ({ ...prev, fixStatus: 'failed' }));
    } finally {
      setIsApplying(false);
    }
  };

  const handleGenerateTests = async (e) => {
    e.stopPropagation();
    if (!effectiveAnalysisId || !issueState._id || isGeneratingTests) return;
    setIsGeneratingTests(true);
    setGeneratedTestContent('');
    setTestApplyError('');
    try {
      const result = await generateIssueTests(effectiveAnalysisId, issueState._id);
      setGeneratedTestContent(result.testContent);
      setExpanded(true); // Automatically expand to show generated tests
      toast.success('Regression unit tests generated by Gemini.', 'Tests Generated');
    } catch (err) {
      const msg = err.response?.data?.message || err.message || 'Failed to generate tests.';
      setTestApplyError(msg);
      toast.error(msg, 'Test Generation Failed');
    } finally {
      setIsGeneratingTests(false);
    }
  };

  const handleApplyTests = async (e) => {
    e.stopPropagation();
    if (!effectiveAnalysisId || !issueState._id || isApplyingTests || !generatedTestContent) return;
    setIsApplyingTests(true);
    setTestApplyError('');
    setTestApplySuccess('');
    try {
      const result = await applyIssueTests(effectiveAnalysisId, issueState._id, generatedTestContent);
      setIssueState((prev) => ({
        ...prev,
        ...result.issue,
        testBranch: result.branch,
        testCompareUrl: result.compareUrl,
      }));
      setTestApplySuccess(`Tests committed to branch "${result.branch}".`);
      toast.success(`Tests committed to "${result.branch}".`, 'Tests Applied');
    } catch (err) {
      const msg = err.response?.data?.message || err.message || 'Failed to apply tests.';
      setTestApplyError(msg);
      toast.error(msg, 'Apply Tests Failed');
    } finally {
      setIsApplyingTests(false);
    }
  };

  return (
    <div
      className={`overflow-hidden rounded-xl border transition-all ${
        expanded
          ? 'border-graphite-600 bg-graphite-900 shadow-panel-hover'
          : 'border-graphite-750 bg-graphite-900/90 hover:border-graphite-600 hover:bg-graphite-850/60'
      }`}
    >
      {/* Clickable Header */}
      <div
        role="button"
        tabIndex={0}
        onClick={() => setExpanded((e) => !e)}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') setExpanded((exp) => !exp);
        }}
        className="flex w-full cursor-pointer items-start justify-between gap-3.5 p-4 text-left transition-colors"
      >
        <div className="min-w-0 flex-1 space-y-2">
          {/* Metadata badges */}
          <div className="flex flex-wrap items-center gap-2">
            <span
              className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-[10px] font-mono font-semibold uppercase tracking-wider ${cfg.bg} ${cfg.border} ${cfg.text} border`}
            >
              <span className={`h-1.5 w-1.5 rounded-full ${cfg.dot}`} />
              {cfg.label}
            </span>

            <span className="rounded-full border border-graphite-700 bg-graphite-800 px-2 py-0.5 text-[10px] font-mono uppercase tracking-wider text-mist-400">
              {categoryLabels[issueState.category] || issueState.category}
            </span>

            <span className="inline-flex items-center gap-1.5 rounded-md bg-graphite-800/90 px-2.5 py-0.5 font-mono text-[11px] text-mist-300 border border-graphite-700 max-w-[280px] sm:max-w-md truncate">
              <svg className="h-3 w-3 text-mist-400 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
              </svg>
              <span className="truncate">{issueState.file}</span>
              {issueState.line ? <span className="text-amber-400 font-bold">:{issueState.line}</span> : null}
            </span>

            {issueState.repository && (
              <a
                href={issueState.repository.htmlUrl}
                target="_blank"
                rel="noreferrer"
                onClick={(e) => e.stopPropagation()}
                className="truncate rounded-full border border-graphite-700 bg-graphite-800 px-2 py-0.5 text-[10px] font-mono text-amber-400 hover:text-amber-300 hover:underline"
              >
                {issueState.repository.fullName}
              </a>
            )}

            {issueState.fixStatus === 'applied' && (
              <span className="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-0.5 text-[10px] font-mono font-semibold uppercase tracking-wider text-emerald-400">
                Fix Applied ✓
              </span>
            )}

            {issueState.prUrl && (
              <a
                href={issueState.prUrl}
                target="_blank"
                rel="noreferrer"
                onClick={(e) => e.stopPropagation()}
                className="rounded-full border border-purple-500/40 bg-purple-500/10 px-2 py-0.5 text-[10px] font-mono font-semibold uppercase tracking-wider text-purple-300 hover:underline"
              >
                PR #{issueState.prNumber} Open ↗
              </a>
            )}
          </div>

          {/* Description */}
          <p className="text-xs sm:text-sm font-medium text-mist-100 leading-snug">
            {issueState.description}
          </p>
        </div>

        {/* Expand toggle */}
        <div className="flex items-center gap-1 shrink-0 pt-0.5">
          <span className="text-xs text-mist-500 hidden sm:inline font-mono">
            {expanded ? 'Hide details' : 'View details'}
          </span>
          <span className="flex h-6 w-6 items-center justify-center rounded-lg border border-graphite-700 bg-graphite-800 text-mist-400 text-xs font-mono">
            {expanded ? '−' : '+'}
          </span>
        </div>
      </div>

      {/* Expanded details */}
      {expanded && (
        <div className="border-t border-graphite-750 bg-graphite-950/60 p-4 sm:p-5 text-xs sm:text-sm space-y-4 animate-fade-in">
          {/* Recommendation */}
          <div>
            <div className="flex items-center gap-1.5 text-xs font-mono font-semibold uppercase tracking-wider text-amber-400/90 mb-1.5">
              <svg className="h-3.5 w-3.5 text-amber-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M9 18h6" />
                <path d="M10 22h4" />
                <path d="M15.09 14c.18-.98.65-1.74 1.41-2.5A4.65 4.65 0 0 0 18 8 6 6 0 0 0 6 8c0 1 .23 2.23 1.5 3.5A4.61 4.61 0 0 1 8.91 14" />
              </svg>
              <span>Remediation Recommendation</span>
            </div>
            <p className="text-mist-300 leading-relaxed bg-graphite-900/80 border border-graphite-750 rounded-lg p-3">
              {issueState.recommendation}
            </p>
          </div>

          {/* Suggested Fix */}
          {issueState.suggestedFix && (
            <div>
              <div className="flex items-center justify-between text-xs font-mono font-semibold uppercase tracking-wider text-mist-400 mb-1.5">
                <span className="flex items-center gap-1.5 text-emerald-400">
                  <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" fill="currentColor" />
                  </svg>
                  <span>Suggested Fix Diff</span>
                </span>
                <CopyCodeButton text={issueState.suggestedFix} />
              </div>

              <pre className="overflow-x-auto rounded-lg border border-graphite-700 bg-graphite-950 p-3.5 font-mono text-xs text-amber-300/90 leading-relaxed shadow-inner">
                <code>{issueState.suggestedFix}</code>
              </pre>

              <p className="mt-1.5 text-[11px] text-mist-500">
                {readOnly
                  ? 'Reference fix recommendation.'
                  : 'Click "Apply Fix" below to have Gemini update the file and commit to a new Git branch.'}
              </p>
            </div>
          )}

          {/* Actions toolbar */}
          <div className="flex flex-wrap items-center gap-2.5 border-t border-graphite-800 pt-3">
            {issueState.fixStatus === 'applied' && issueState.fixCompareUrl ? (
              <div className="flex flex-wrap items-center gap-2">
                <a
                  href={issueState.fixCompareUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="btn-secondary text-xs text-emerald-400 border-emerald-500/30 bg-emerald-500/10 hover:bg-emerald-500/20"
                >
                  <span>View Fix Branch</span>
                  <span>↗</span>
                </a>
                {!readOnly && (
                  issueState.prUrl ? (
                    <a
                      href={issueState.prUrl}
                      target="_blank"
                      rel="noreferrer"
                      className="btn-ai text-xs"
                    >
                      PR #{issueState.prNumber} Open ↗
                    </a>
                  ) : (
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        setPrModalBranchType('fix');
                        setIsPrModalOpen(true);
                      }}
                      className="btn-primary text-xs"
                    >
                      Create Pull Request
                    </button>
                  )
                )}
              </div>
            ) : !readOnly ? (
              <button
                onClick={handleApplyFix}
                disabled={isApplying}
                className="btn-primary text-xs"
              >
                {isApplying ? (
                  <>
                    <span className="h-2 w-2 rounded-full bg-graphite-950 animate-ping" />
                    <span>Applying fix…</span>
                  </>
                ) : (
                  <>
                    <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                      <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" fill="currentColor" />
                    </svg>
                    <span>Apply Fix</span>
                  </>
                )}
              </button>
            ) : null}

            {!readOnly && (
              <button
                onClick={handleGenerateTests}
                disabled={isGeneratingTests}
                className="btn-secondary text-xs"
              >
                {isGeneratingTests ? (
                  <>
                    <span className="h-2 w-2 rounded-full bg-amber-400 animate-ping" />
                    <span>Generating Tests…</span>
                  </>
                ) : (
                  <>
                    <svg className="h-3.5 w-3.5 text-sky-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M10 2v7.31M14 2v7.31M8.5 2h7M14 9.3a6.5 6.5 0 1 1-4 0" />
                    </svg>
                    <span>Generate Tests</span>
                  </>
                )}
              </button>
            )}

            {issueState.fixBranch && issueState.fixStatus === 'applied' && (
              <span className="font-mono text-[11px] text-mist-500">
                branch: <code className="text-mist-300">{issueState.fixBranch}</code>
              </span>
            )}
          </div>

          {applyError && (
            <p className="rounded-lg border border-rose-500/30 bg-rose-500/10 p-2.5 text-xs text-rose-300 font-mono">
              {applyError}
            </p>
          )}

          {/* Generated Tests Section */}
          {generatedTestContent && (
            <div className="mt-4 border-t border-graphite-800 pt-3.5 space-y-2.5">
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-1.5 text-xs font-mono font-semibold uppercase tracking-wider text-sky-400">
                  <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M10 2v7.31M14 2v7.31M8.5 2h7M14 9.3a6.5 6.5 0 1 1-4 0" />
                  </svg>
                  <span>Generated Regression Tests</span>
                </span>
                <CopyCodeButton text={generatedTestContent} />
              </div>

              <pre className="max-h-64 overflow-x-auto rounded-lg border border-graphite-700 bg-graphite-950 p-3.5 font-mono text-xs text-sky-300/90 leading-relaxed shadow-inner">
                <code>{generatedTestContent}</code>
              </pre>

              <div className="flex flex-wrap items-center gap-2.5 pt-1">
                <button
                  onClick={handleApplyTests}
                  disabled={isApplyingTests}
                  className="btn-success text-xs"
                >
                  {isApplyingTests ? 'Committing Tests…' : 'Apply Tests to Repository'}
                </button>

                {issueState.testBranch && (
                  <div className="flex flex-wrap items-center gap-2">
                    <a
                      href={issueState.testCompareUrl}
                      target="_blank"
                      rel="noreferrer"
                      className="btn-secondary text-xs text-emerald-400 border-emerald-500/30 bg-emerald-500/10 hover:bg-emerald-500/20"
                    >
                      View test branch →
                    </a>
                    {!readOnly && (
                      issueState.prUrl ? (
                        <a
                          href={issueState.prUrl}
                          target="_blank"
                          rel="noreferrer"
                          className="btn-ai text-xs"
                        >
                          PR #{issueState.prNumber} Open ↗
                        </a>
                      ) : (
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            setPrModalBranchType('test');
                            setIsPrModalOpen(true);
                          }}
                          className="btn-primary text-xs"
                        >
                          Create Pull Request
                        </button>
                      )
                    )}
                  </div>
                )}

                {testApplySuccess && !issueState.testBranch && (
                  <span className="text-xs text-emerald-400 font-mono">{testApplySuccess}</span>
                )}
                {testApplyError && (
                  <span className="text-xs text-rose-400 font-mono">{testApplyError}</span>
                )}
              </div>
            </div>
          )}
        </div>
      )}

      {/* PR Creation Modal */}
      <CreatePrModal
        isOpen={isPrModalOpen}
        onClose={() => setIsPrModalOpen(false)}
        analysisId={effectiveAnalysisId}
        issue={issueState}
        branchType={prModalBranchType}
        onPrCreated={(pr, updatedIssue) => {
          setIssueState((prev) => ({
            ...prev,
            ...(updatedIssue || {}),
            prUrl: pr.htmlUrl,
            prNumber: pr.number,
            prStatus: 'created',
          }));
          toast.success(`Pull Request #${pr.number} created on GitHub.`, 'PR Created');
        }}
      />
    </div>
  );
}

export default function IssueList({
  issues = [],
  analysisId,
  readOnly = false,
  activeFilter,
  onFilterChange,
}) {
  const [internalFilter, setInternalFilter] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');

  const currentFilter = activeFilter !== undefined ? activeFilter : internalFilter;
  const setFilter = onFilterChange || setInternalFilter;

  // Counts by severity
  const counts = useMemo(() => {
    return {
      all: issues.length,
      critical: issues.filter((i) => i.severity === 'critical').length,
      high: issues.filter((i) => i.severity === 'high').length,
      medium: issues.filter((i) => i.severity === 'medium').length,
      low: issues.filter((i) => i.severity === 'low').length,
    };
  }, [issues]);

  const filtered = useMemo(() => {
    let sorted = [...issues].sort(
      (a, b) => severityOrder[a.severity] - severityOrder[b.severity]
    );

    if (currentFilter !== 'all') {
      sorted = sorted.filter((i) => i.severity === currentFilter);
    }

    const q = searchQuery.trim().toLowerCase();
    if (q) {
      sorted = sorted.filter((i) => {
        return (
          i.file?.toLowerCase().includes(q) ||
          i.description?.toLowerCase().includes(q) ||
          i.recommendation?.toLowerCase().includes(q) ||
          i.category?.toLowerCase().includes(q)
        );
      });
    }

    return sorted;
  }, [issues, currentFilter, searchQuery]);

  if (issues.length === 0) {
    return (
      <div className="rounded-2xl border border-dashed border-emerald-500/20 bg-emerald-500/5 p-8 text-center">
        <div className="mx-auto mb-2 flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
          <svg className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path
              fillRule="evenodd"
              d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
              clipRule="evenodd"
            />
          </svg>
        </div>
        <h3 className="text-sm font-semibold text-emerald-400 font-mono">Zero Issues Detected</h3>
        <p className="mx-auto mt-1 max-w-sm text-xs text-mist-400">
          Clean scan. No critical bugs, security vulnerabilities, or code smells identified.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Controls: Filter Pills & Search */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-wrap gap-1.5">
          {['all', 'critical', 'high', 'medium', 'low'].map((key) => {
            const count = counts[key];
            const isSelected = currentFilter === key;

            return (
              <button
                key={key}
                type="button"
                onClick={() => setFilter(key)}
                className={`inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1 text-xs font-medium capitalize transition-colors ${
                  isSelected
                    ? 'bg-amber-400 text-graphite-950 font-semibold shadow-sm'
                    : 'border border-graphite-750 bg-graphite-900 text-mist-400 hover:text-mist-100 hover:bg-graphite-800'
                }`}
              >
                <span>{key}</span>
                <span
                  className={`rounded-full px-1.5 py-0.2 text-[10px] font-mono ${
                    isSelected ? 'bg-graphite-950/20 text-graphite-950 font-bold' : 'bg-graphite-800 text-mist-400'
                  }`}
                >
                  {count}
                </span>
              </button>
            );
          })}
        </div>

        {/* Search filter */}
        <div className="relative max-w-xs w-full">
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Filter issues by file or keyword…"
            className="w-full rounded-lg border border-graphite-750 bg-graphite-900 py-1.5 pl-8 pr-7 text-xs text-mist-100 outline-none transition-colors placeholder:text-mist-500 focus:border-amber-400"
          />
          <svg
            className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-mist-500"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <circle cx="11" cy="11" r="8" />
            <line x1="21" x2="16.65" y1="21" y2="16.65" />
          </svg>
          {searchQuery && (
            <button
              onClick={() => setSearchQuery('')}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-mist-500 hover:text-mist-200"
              aria-label="Clear issue search"
            >
              <svg className="h-3.5 w-3.5" viewBox="0 0 20 20" fill="currentColor">
                <path
                  fillRule="evenodd"
                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                  clipRule="evenodd"
                />
              </svg>
            </button>
          )}
        </div>
      </div>

      {/* Issue rows */}
      {filtered.length === 0 ? (
        <div className="rounded-xl border border-dashed border-graphite-750 bg-graphite-900/60 p-8 text-center">
          <p className="text-xs text-mist-400 font-mono">
            No issues match the selected filter ({currentFilter}) or search query.
          </p>
          <button
            onClick={() => {
              setFilter('all');
              setSearchQuery('');
            }}
            className="mt-2 text-xs text-amber-400 hover:underline font-mono"
          >
            Clear filters
          </button>
        </div>
      ) : (
        <div className="flex flex-col gap-2.5">
          {filtered.map((issue, idx) => (
            <IssueRow
              key={issue._id || idx}
              issue={issue}
              analysisId={analysisId}
              readOnly={readOnly}
            />
          ))}
        </div>
      )}
    </div>
  );
}